name: tf2-face-detection-recognition
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - tensorflow-gpu
  - numpy
  - opencv=4.1.1=py37he03da11_2
  - pandas=0.25.1=py37ha925a31_0
  - pillow=6.1.0=py37hdc69c19_0
  # - pip: